export interface Fixture {
    id:number, 
    division:number,
    round:number,
    hteam:string,
    hteamscore:string,
    ateamscore:string,
    ateam:string,
    hgls:number,
    h2pts:number,
    h1pts:number,
    hteamtotal:number,
    agls:number,
    a2pts:number,
    a1pts:number,
    ateamtotal:number,
}
